package com.gitee.taven.mapper;

import com.gitee.taven.entity.Users;
import com.gitee.taven.entity.UsersExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

public interface UsersMapper {


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Oct 30 21:13:41 CST 2018
	 */
	int insertSelective(Users record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Oct 30 21:13:41 CST 2018
	 */
/*	@Update("update users set " +
			"        username = #{username,jdbcType=VARCHAR}, " +
			"       password = #{password,jdbcType=VARCHAR}, " +
			"      token = #{token,jdbcType=VARCHAR}, " +
			"      last_login_time = #{lastLoginTime,jdbcType=TIMESTAMP} " +
			"    where id = #{id,jdbcType=INTEGER}")*/
	int updateByPrimaryKeySelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Oct 30 21:13:41 CST 2018
	 */
	int updateByPrimaryKey(Users record);
}